media: src/content/media
content:
  - name: sections
    label: Sektioner
    type: collection
    path: src/content/sections
    fields: 
      - { name: title, label: Titel, type: string }
      - { name: body, label: Innehåll, type: rich-text }
      - { name: image, label: Bild, type: image }
      - { name: columns, label: Kolumner, type: boolean, default: false }
      - { name: order, label: Sortering, type: number }